from enum import Enum


class Country(Enum):
    ALBANIA = "Albania"
    AUSTRALIA = "Australia"
    BELGIUM = "Belgia"
    BRASIL = "Brasilia"
    BULGARIA = "Bulgaria"
    COSTA_RICA = "Costa Rica"
    EGYPT = "Egypti"
    SPAIN = "Espanja"
    SOUTH_AFRICA = "Etelä-Afrikka"
    FILIPPINES = "Filippiinit"
    GAMBIA = "Gambia"
    INDONESIA = "Indonesia"
    ITALY = "Italia"
    CANADA = "Kanada"
    GREECE = "Kreikka"
    CROATIA = "Kroatia"
    CYPRUS = "Kypros"
    MEXICO = "Meksiko"
    NORWAY = "Norja"
    PANAMA = "Panama"
    PORTUGAL = "Portugali"
    FRANCE = "Ranska"
    SWEDEN = "Ruotsi"
    GERMANY = "Saksa"
    FINLAND = "Suomi"
    SWITZERLAND = "Sveitsi"
    DENMARK = "Tanska"
    THAILAND = "Thaimaa"
    TURKEY = "Turkki"
    USA = "USA"
    HUNGARY = "Unkari"
    RUSSIA = "Venäjä"
    ESTONIA = "Viro"


class HoldingType(Enum):
    OWN = "Oma"
    PARTIAL_OWNERSHIP = "Osaomistus"
    RIGHT_OF_OCCUPANCY = "Asumisoikeus"
    OTHER = "Muu"
    RENT = "Vuokra"
    PARTIAL_RENT = "Vuokrataan osa kiinteistöstä"


class ItemGroup(Enum):
    DWELLING = "Asunnot"
    HOLIDAY_APARTMENT = "Lomakohteet"
    OFFICE = "Toimitilat"
    RENTAL = "Vuokra-asunnot"
    ESTATE = "Maa- ja metsätilat"
    LOT = "Tontit"
    NEW_BUILDING = "Uudiskohteet"
    CARAGE_OR_OTHER = "Autotallit ja muut"


class RealtyGroup(Enum):
    RESIDENTIAL_APARTMENT = "asuinhuoneisto"
    RESIDENTIAL_PROPERTY = "asuinkiinteistö"
    NEW_BUILDING = "uudiskohde"
    RENTAL_APARTMENT = "vuokrahuoneisto"
    RENTAL_PROPERTY = "vuokrattava asuinkiinteistö"
    HOLIDAY_APARTMENT = "lomahuoneisto"
    HOLIDAY_PROPERTY = "lomakiinteistö"
    ESTATE = "maa- ja metsätila"
    CARAGE_AND_OTHER = "autotalli ja muu"
    LOT = "tontti"
    OFFICE = "toimitila"


class RealtyType(Enum):
    BLOCK_OF_FLATS = "Kerrostalo"
    ROW_HOUSE = "Rivitalo"
    HOUSE = "Omakotitalo"
    DUPLEX = "Paritalo"
    DETACHED_HOUSE = "Erillistalo"
    WOODEN_HOUSE_DEPARTMENT = "Puutalo-osake"
    OTHER = "Muut"
    BALCONY_ACCESS_HOUSE = "Luhtitalo"
    APARTMENT_ABROAD = "Huoneisto ulkomailla"
    SUMMER_COTTAGE_OR_VILLA = "Kesämökki tai huvila"
    TIME_SHARE = "Lomaosake"
    VACATION_APARTMENT = "Lomahuoneisto"
    FARM = "Maatila"
    FOREST_PROPERTY = "Metsatila"
    FIELD_AREA = "Peltoalue"
    UNSEPARATED_PARCEL = "Maaraala"
    WILDERNESS_AREA = "Eramaaalue"
    RESIDENTIAL_PLOT = "Okttontti"
    LEISURE_PLOT = "Vapaaajantontti"
    OTHER_PLOT = "Muutontti"
    CARPORT = "Autokatos"
    PARKING_SPACE = "Autopaikka"
    GARAGE = "Autotalli"
    GARAGE_SPACE = "Autohallipaikka"
    BERTH = "Venepaikka"
    STORAGE_SPACE = "Varastotila"
    BUSINESS_PREMISES = "Toimitila"


class TradeType(Enum):
    SALE = "myynti"
    RENT = "vuokraus"
    SALE_OR_RENT = "myynti tai vuokraus"
    PART_OWNERSHIP = "osaomistus"
    RIGHT_OF_OCCUPANCY = "asumisoikeus"
    PARTIAL_RENT = "vuokrataan osa kiinteistöä"
    OTHER = "muu"


class LinkType(Enum):
    EXTRA_VISIBILITY = "Lisänäkyvyyslinkki"
    EXTRA_INFO_1 = "Lisätietolinkki 1"
    EXTRA_INFO_2 = "Lisätietolinkki 2"
    EXTRA_INFO_3 = "Lisätietolinkki 3"
    EXTRA_INFO_4 = "Lisätietolinkki 4"
    EXTRA_INFO_5 = "Lisätietolinkki 5"
    AD_1 = "Mainos 1"
    AD_2 = "Mainos 2"
    AD_3 = "Mainos 3"
    AD_4 = "Mainos 4"
    AD_5 = "Mainos 5"
    AD_6 = "Mainos 6"
    PDF_PRESENTATION = "PDF -esitteen linkki"
    DETAILED_PRESENTATION = "Tarkempiesittelylinkki"
    NEW_HOUSE = "Uudiskohdelinkki"
    SEARCH_WATCH_AD = "Vahtiviestimainos"
    VIDEO = "Videolinkki"
    VIRTUAL = "Virtuaalilinkki"
    COLORING_PROGRAM = "Väritysohjelmalinkki"
    LANDING_PAGE = "Kohdesivulinkki"


class RealtyImageType(Enum):
    MAIN_IMAGE = "pääkuva"
    FLOOR_PLAN = "pohjakuva"
    GENERAL_IMAGE = "yleiskuva"
